### ISSUE TITLE
select all check box not changing

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-interactive-table-card-changelog#1]
![vd](https://user-images.githubusercontent.com/6344066/97264603-3af51780-1860-11eb-982b-a86ee0b7e2f1.gif)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. The bug has been fixed. 

You will need to update the JS of the Interactive Table component. You can get it here:
https://codyhouse.co/ds/components/app/interactive-table

Cheers!
